### ISSUE TITLE
Any interest in using postgres notifications?

### ISSUE THREAD

**Issue by benwilson512** [mbuhot/ecto_job#27]
Hey folks!

I'm looking at switching out our home grown postgres based job library with ecto_job. One thing we do however is have a trigger on the queue table that does a `pg_notify` to a `jobs` topic. Then there's a Postgrex.Notifications process that listens for these and uses it to trigger a job fetch.

Notably, this is NOT used to replace getting the rows out of the database with `lock: "FOR UPDATE SKIP LOCKED"`. It does replacing the polling however, and decreases the overall latency.

Any interest in having a PR that adds this (perhaps optionally?) to ecto_job?

**Comment by mbuhot** [comment]
Ecto_job is primarily based on pg_notify 😄

Polling is used to handle scheduled jobs, retries and timeout detection, but it is intended to be fairly infrequent, eg once per minute.

Now is a great time to take it for a spin and suggest any new features, since we need to update it for ecto 3.0 👍

**Comment by mbuhot** [comment]
For reference the notify trigger is in the migrations file: https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/migrations.ex

**Comment by mbuhot** [comment]
This issue has been quiet for a while so closing for now. Please re-open if I've misunderstood something.
