### ISSUE TITLE
completed jobs

### ISSUE THREAD

**Issue by henry-hz** [mbuhot/ecto_job#3]
Hi,
pls, is there any configuration or explicit message to send that marks jobs as completed ?
After running my jobs, the state continues as "IN PROGRESS".

Do you think that a  configurable cleaner job should be made to clean the completed jobs after X time ?

**Comment by mbuhot** [comment]
Completed jobs should be deleted by passing the Multi to Repo.transaction.

https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/job_queue.ex#L287

Is that failing?

**Comment by henry-hz** [comment]
it's working, sorry, my fault, i forgot to finish with MyApp.Repo.transaction() to signal ecto_job that it was done. thanks :)
