### ISSUE TITLE
Negative Demand Errors

### ISSUE THREAD

**Issue by seangeo** [mbuhot/ecto_job#38]
Hi there.

We've got EctoJob running on a reasonably busy queue and have recent started getting error reports such as these:

```
ERROR 2201W (invalid_row_count_in_limit_clause) LIMIT must not be negative
```

We were able to trace this back to a negative demand in the Producer state, for example:

```
%EctoJob.Producer.State{clock: &DateTime.utc_now/0, demand: -31, execution_timeout: 300000, notifications_listen_timeout: 5000, notifier: #PID<0.2601.0>, poll_interval: 60000, repo: Repo, reservation_timeout: 60000, schema: JobQueue}
```

After a bit of digging and debugging, we narrowed the error down to this part of the code: https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/producer.ex#L184-L185

The `count` returned by `JobQueue.reserve_available_jobs` is greater than the `demand`, which results in the demand being updated to a negative number in the Producer's state. Then the following handle_demand fails.

We dug into this a little more, because, looking the `JobQueue.reserve_available_jobs` query it looks like this shouldn't be happening, because the limit is applied. Then we found [this](https://github.com/feikesteenbergen/demos/blob/master/bugs/update_from_correlated.adoc). Basically, there's an issue with using limit in a subquery of an update which can result in the limit being ignored if the query planner chooses a Nested Loop in the execution plan. 

The work around for this is to use a CTE, however Ecto doesn't support that. There is a [PR on Ecto](https://github.com/elixir-ecto/ecto/pull/2757) to add support for CTEs, after which you'd be able to apply the work around (I hope). I couldn't find any other way to get Ecto to use a CTE.

**Comment by mbuhot** [comment]
Thanks for the detailed bug report @seangeo 👍 
Sorry that this caused problems for you.

A CTE sounds like a good approach. 

The code is fairly self contained, would you like to send a PR to replace the implementation `reserve_available_jobs` with a call to `Ecto.Adapters.SQL.query` with the an inline sql string containing the CTE and update statement?
