### ISSUE TITLE
LogLevel in configuration

### ISSUE THREAD

**Issue by zdeneksejcek** [mbuhot/ecto_job#50]
Hi,

I tried to set log_level in configuration (according to readme), but it still logs like crazy. Is this functionality working?

I just try to get rid of rather useless reoccurring log messages in iex shell.

Thanks!

**Comment by zdeneksejcek** [comment]
Hi, any news on this issue?

**Comment by mbuhot** [comment]
There are two configuations you can use to control logs:

```elixir
log: true,  # set this to false to turn off logging
log_level: :debug # This setting controls the severity level at which the logs are output. 
```

Setting the level doesn't change the amount of logs or do any filtering. It only changes the severity of the messages themselves.

See https://github.com/mbuhot/ecto_job/blob/c4ebaa53fef0c6da5d77b0765c52b78c503391e3/lib/ecto_job/worker.ex#L32-L37
