### ISSUE TITLE
Use clock from database rather than application?

### ISSUE THREAD

**Issue by bgentry** [mbuhot/ecto_job#51]
Hi there, thanks for making EctoJob! I've been evaluating it recently to possibly use it at our company.

One of the things I noticed while skimming the source is the number of places where you're generating the current time in application code. This jumped out at me given the number of times I've seen issues caused by distributed application servers whose system clocks are not perfectly in sync, timezone misconfigurations, etc 😩

Given that Postgres has [a `now()` function](https://www.postgresql.org/docs/current/functions-datetime.html#id-1.5.8.14.5.2.2.26.1.1) to fetch the current time from the start of the in-progress transaction, and given that this function wouldn't susceptible to skewed clocks, I wondered if you've given any thought to using on the time from the database rather than always calling `DateTime.utc_now()`. It wouldn't necessarily protect you from issues arising from scheduled jobs, but it might eliminate whole classes of other potential problems.

**Comment by mbuhot** [comment]
Hi @bgentry, thanks for checking out ecto_job.

Reading the current time from the DB makes sense for job scheduling and expiry 👍 

Would you be willing to send a PR?

It looks like you could remove the `now` parameter from most of the functions in the [job_queue.ex](https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/job_queue.ex#L210) module, then remove the `DateTime.utc_now` calls from the calling code.
