### ISSUE TITLE
Publish 3.0 to hex.pm

### ISSUE THREAD

**Issue by brandonjoyce** [mbuhot/ecto_job#54]
It appears that 3.0 is not published to hex.pm. Is there a plan to do that soonish?  I like that the indexes were added to some columns. Nice project btw!

EDIT: Is 3.0 still in dev?

**Comment by mbuhot** [comment]
@brandonjoyce I'm waiting for Ecto 3.2 to be released, as the current ecto_job implementation depends on the CTE support added in ecto recently.

**Comment by zacksiri** [comment]
@mbuhot i believe ecto 3.2 is released

**Comment by mbuhot** [comment]
Thanks @zacksiri I should get a new release out this week.

**Comment by zacksiri** [comment]
@mbuhot you can close this. thank you!
