### ISSUE TITLE
perform later?

### ISSUE THREAD

**Issue by strzibny** [mbuhot/ecto_job#55]
We started to use `ecto_job` on the project I am working on, but I cannot find if it's possible to schedule a job for running later (e.g. 30 minutes after it's schedule, and not before). I very used to this feature from other job processing libraries such as Sidekiq. Is it supported? If not, are you planning on adding something like this?

**Comment by mbuhot** [comment]
To clarify, you’d like to re-schedule a job from within its `perform`function? 

Sounds like a useful feature. 👍Would you be interested in sending a pull request?

I’m personally not adding new features to ecto_job, but happy to review and assist with contributions.

**Comment by strzibny** [comment]
I just found about `|> MyApp.JobQueue.new(schedule: xx)`. If that works, I think I can live without it. Thanks for the info!

**Comment by mbuhot** [comment]
:D
