### ISSUE TITLE
Infinity Number of Max Attempt

### ISSUE THREAD

**Issue by blisscs** [mbuhot/ecto_job#59]
Hi, 

Is there a way to set max_attempt infinity?

**Comment by mbuhot** [comment]
No, but you can use a very large integer.

If you were to retry a job with a 1 second delay 2^31 times (2147483648), it would keep trying for 68 years before giving up.

**Comment by blisscs** [comment]
Thanks @mbuhot 

I will set a very large integer value for that instead.
