### ISSUE TITLE
Using Multiple Queues

### ISSUE THREAD

**Issue by blisscs** [mbuhot/ecto_job#60]
Hi, 

I am wondering if I could set max demands per job_type. 

The scenario is like this - I have two kinds of jobs, which are 1. sequential jobs (job processing is one at a time), 2. parallel jobs (job processings are done many at a time)

How can I use ecto_job to accommodate these kinds of jobs?

**Comment by mbuhot** [comment]
@blisscs Yes you can start multiple queues in your supervision tree.

```elixir
def start(_type, _args) do

  children = [
    MyApp.Repo,
    {MyApp.SlowQueue, repo: MyApp.Repo, max_demand: 1},
    {MyApp.FastQueue, repo: MyApp.Repo, max_demand: 10}
  ]

  opts = [strategy: :one_for_one, name: MyApp.Supervisor]
  Supervisor.start_link(children, opts)
end
```

However, EctoJob can't guarantee that processing is one at a time if there are multiple nodes running your application. The `max_demand` setting applies locally to the current node. So you'd need some additional locking or ensure that there's only a single instance of your application running.

**Comment by blisscs** [comment]
@mbuhot thank you for recommending the way to use multiple job queues.

In `MyApp.SlowQueue` and `MyApp.FastQueue` I can use the same database table, right?

One more concern that I am having is that if I have JobQueue processes (with the same module name and definition) running on different nodes, does the ecto_job guarantee that when the notification is fired for the next job to be handled only one process (from all the job queue processes on all nodes connected) is selected to process that job or all of the processes will be notified to do the same jobs.

**Comment by mbuhot** [comment]
> In MyApp.SlowQueue and MyApp.FastQueue I can use the same database table, right?

No, each queue requires its own table. 

> does the ecto_job guarantee that when the notification is fired for the next job to be handled only one process (from all the job queue processes on all nodes connected) is selected to process that job

EctoJob will notify all nodes. Only one process will successfully reserve the job in the DB, using `select for update ... skip locked`.

**Comment by blisscs** [comment]
Hi
When trying to run migration for the second job table(with different job table name).
We are getting the following error - 

```
11:25:21.651 [info]  execute "CREATE FUNCTION fn_notify_inserted()\n  RETURNS trigger AS $$\nDECLARE\nBEGIN\n  PERFORM pg_notify(TG_TABLE_NAME, '');\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql\n"
** (Postgrex.Error) ERROR 42723 (duplicate_function) function "fn_notify_inserted" already exists with same argument types
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:716: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:166: :timer.tc/1
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7
    (ecto_sql) lib/ecto/migrator.ex:242: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto_sql) lib/ecto/migrator.ex:324: anonymous fn/3 in Ecto.Migrator.run_maybe_in_transaction/6
    (ecto_sql) lib/ecto/adapters/sql.ex:898: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
    (ecto_sql) lib/ecto/migrator.ex:323: Ecto.Migrator.run_maybe_in_transaction/6
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

It seems that the ecto_job migration code is using the same notification function name that causes Postgres to block the creation of a new notification function for another job queue table.

**Comment by mbuhot** [comment]
The [Install](https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/migrations.ex#L11-L52) migration only needs to be run once.

The [CreateJobTable](https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/migrations.ex#L54-L129) migration should be run once per queue.

**Comment by blisscs** [comment]
Thank you very much @mbuhot

The issue is resolved.
