### ISSUE TITLE
Non-concurrent queue

### ISSUE THREAD

**Issue by strzibny** [mbuhot/ecto_job#63]
Hello,

can a queue be processed one job after another?

The use-case is generating invoices where the transaction would fail if the invoice has the same number so the jobs needs to run one after another.

As I understand it I could move all single jobs (per customer) to be one big job to avoid running into possible transaction failures, but before that I wanted to explore if there is a possibility to simply run them in sequence.

I can imagine this might be useful to other use-cases too.

**Comment by mbuhot** [comment]
Hi @strzibny 👋 

I would suggest moving the sequential jobs into a separate queue, with a `max_demand` value set to 1. This will give you sequential processing on each node.

```elixir
def start(_type, _args) do
  children = [
    MyApp.Repo,
    {MyApp.GeneralJobQueue, repo: MyApp.Repo, max_demand: 10},
    {MyApp.SequentialJobQueue, repo: MyApp.Repo, max_demand: 1}
  ]

  opts = [strategy: :one_for_one, name: MyApp.Supervisor]
  Supervisor.start_link(children, opts)
end
```

To guarantee sequential processing across multiple nodes, you need a lock of some kind.
Thanks to EctoJob's transactional processing, you can acquire a postgresql lock within your job.

In the example below, it locks the entire invoices table (you could alternatively use a [pg_advisory_xact_lock](https://www.postgresql.org/docs/12/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS) for a more fine-grained lock).

```elixir
defmodule MyApp.SequentialJobQueue do
  use EctoJob.JobQueue, table_name: "sequential_jobs"
  alias Ecto.Adapters.SQL
  alias MyApp.Repo

  def perform(multi, %{"type" => "generate_invoice"} = params) do
    multi
    |> Multi.run(:acquire_lock, fn (repo, _changes) -> SQL.query(repo, "LOCK invoices") end)
    |> Multi.run(:do_work, fn (repo, _changes) -> generate_invoice(params) end)
    |> Repo.transaction()
  end
end
```

**Comment by strzibny** [comment]
Thank you, that's super helpful!
