### ISSUE TITLE
Maintainers Wanted!

### ISSUE THREAD

**Issue by mbuhot** [mbuhot/ecto_job#74]
@ramondelemos @lukyanov @jeanparpaillon I'd really like to get your open PRs merged.
Unfortunately I'm only able to work on EctoJob in my free time, and haven't been able to thoroughly test out the changes.

Would any of you like to become a co-maintainer of EctoJob? 

It's generally not a lot of work - EctoJob has been fairly stable over the years. I just like to be careful with updates since a bug in a job queue library could have a big impact on users :)

**Comment by mbuhot** [comment]
@jeanparpaillon has agreed to help out maintaining EctoJob, thanks @jeanparpaillon! 🎉

**Comment by jeanparpaillon** [comment]
You're welcome
